### ISSUE TITLE
[BUG] TorchWebDiscoAlgo missing one positional argument (Dataset) to the superconstructor

### ISSUE THREAD

**Issue by kalihale** [owkin/fedeca#69] opened 2024-11-22 04:08 UTC
On line 117 in torch_webdisco_algo.py, the init for the superclass constructor requires a Dataset parameter. This is not provided and thus exits with an error upon attempting to construct the TorchWebDiscoAlgo class.

This is when using the recommended version of substrafl, 0.46.0.

**Comment by jeandut** [comment] 2024-12-03 14:49
Hey @kalihale we will check that ! Can you provide an MWE ?

**Comment by jeandut** [comment] 2024-12-03 14:55
@kalihale normally dataset `survival_dataset` is passed to it in `fedeca_core.py` through the kwargs argument.

**Comment by honghaoli42** [comment] 2024-12-03 18:13
Thank you for the issue report! As Jean said, more details on how the bug could be reproduced would be very helpful. I did a local fresh install of the package and was able to run the script in the [quickstart](https://github.com/owkin/fedeca/blob/main/quickstart/quickstart.md) page.

Are you trying to implement a custom algorithm using `TorchWebDiscoAlgo`? Apart from what Jean mentioned, another example of such implementation could be found [here](https://github.com/owkin/fedeca/blob/268e85c280faa1e4a091f3044263a0a1bdf3ded0/fedeca/analytics/robust_variance_cox_algo.py#L138), where the `dataset` parameter is passed to the constructor.

**Comment by jeandut** [comment] 2024-12-12 19:10
@kalihale are you still facing the issue ?

**Comment by kalihale** [comment] 2024-12-15 06:53
Sorry for the delay, this ended up on the back burner for a bit. With the explanation, I see this is not a bug. Thanks for sharing the implementation example. It was not clear what should be provided for the dataset, am I correct that it should be a class type provided instead of an instance and how this should be implemented? If you have any written documentation I would appreciate it.

By the way, on a system where a GPU/CUDA is available, the quickstart script results in a tensor error [in the substrafl library](https://github.com/Substra/substrafl/blob/95ecc624c26ea6807fb25e79bfdc430acea7fd17/substrafl/algorithms/pytorch/torch_newton_raphson_algo.py#L140) due to the fact that you cannot convert the GPU tensor to numpy without transferring it to the CPU first. (Torch version 1.13.1, substrafl version 0.46.0) I can create a bug in the substrafl repo for this if you would like if this is still a bug.

**Comment by jeandut** [comment] 2024-12-15 10:42
Hey @kalihale thanks for your comment. The implementation of the algorithm is not very user-friendly in substrafl, however there is some doc here: https://docs.substra.org/en/stable/examples/substrafl/get_started/run_mnist_torch.html.
Indeed you should pass a dataset **class** to the algorithm, the reason is because of both serialization issuesand legacy. Please write an MWE of what you want to do exactly if this is still unclear.

Considering GPU support, please do open an issue on this repository, this is indeed likely a bug.

On a more general note if you use this code and find that some steps are unclear please write issue about improving documentation.

**Comment by jeandut** [comment] 2024-12-15 10:43
I am closing this issue for now, feel free to reopen if you still have problems.

**Closed by jeandut** 2024-12-15 10:43 UTC
Labels: bug
